version = 0.1

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "spirits-dev-customer-searchStore"
s3_bucket = "843219620739-spirits-dev-samdeploy"
s3_prefix = "spirits-dev-customer-searchStore"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Application=\"spirits\" Module=\"customerapi\" Environment=\"dev\" LogLevel=\"INFO\" RetentionInDays=\"30\" NodeLayerArn=\"/spirits/dev/shared/nodelayer/arn\" ESLink=\"https://search-spirits-dev-es-5rxmmgmdh4kmqjbrk566m2cmqq.us-east-1.es.amazonaws.com\""

[sit]
[sit.deploy]
[sit.deploy.parameters]
stack_name = "spirits-sit-customer-searchStore"
s3_bucket = "843219620739-spirits-dev-samdeploy"
s3_prefix = "spirits-sit-customer-searchStore"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Application=\"spirits\" Module=\"customerapi\" Environment=\"sit\" LogLevel=\"INFO\" RetentionInDays=\"30\" NodeLayerArn=\"/spirits/sit/shared/nodelayer/arn\" ESLink=\"https://search-spirits-sit-es-4zcsptd7pfb2okhrb6pdjmcu3e.us-east-1.es.amazonaws.com\""

[prd]
[prd.deploy]
[prd.deploy.parameters]
stack_name = "spirits-prd-customer-searchStore"
s3_bucket = "409907184267-spirits-prd-samdeploy"
s3_prefix = "spirits-prd-customer-searchStore"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Application=\"spirits\" Module=\"customerapi\" Environment=\"prd\" LogLevel=\"INFO\" RetentionInDays=\"30\" NodeLayerArn=\"/spirits/prd/shared/nodelayer/arn\" ESLink=\"https://search-spirits-prd-es-3o7g4umkpikc55dbxkfjgnsgoe.us-east-1.es.amazonaws.com\""
