version = 0.1

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "spirits-dev-customer-CapturePayment"
s3_bucket = "843219620739-spirits-dev-samdeploy"
s3_prefix = "spirits-dev-customer-CapturePayment"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Application=\"spirits\" Module=\"customerapi\" Environment=\"dev\" LogLevel=\"INFO\" RetentionInDays=\"30\" NodeLayerArn=\"/spirits/dev/shared/nodelayer/arn\" EventBusName=\"/spirits/dev/capturePaymentEventBus/name\""

[sit]
[sit.deploy]
[sit.deploy.parameters]
stack_name = "spirits-sit-customer-CapturePayment"
s3_bucket = "843219620739-spirits-dev-samdeploy"
s3_prefix = "spirits-sit-customer-CapturePayment"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Application=\"spirits\" Module=\"customerapi\" Environment=\"sit\" LogLevel=\"INFO\" RetentionInDays=\"30\" NodeLayerArn=\"/spirits/sit/shared/nodelayer/arn\" EventBusName=\"/spirits/dev/capturePaymentEventBus/name\""

[prd]
[prd.deploy]
[prd.deploy.parameters]
stack_name = "spirits-prd-customer-CapturePayment"
s3_bucket = "409907184267-spirits-prd-samdeploy"
s3_prefix = "spirits-prd-customer-CapturePayment"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Application=\"spirits\" Module=\"customerapi\" Environment=\"prd\" LogLevel=\"INFO\" RetentionInDays=\"30\"   NodeLayerArn=\"/spirits/prd/shared/nodelayer/arn\" EventBusName=\"/spirits/dev/capturePaymentEventBus/name\""
