################################################
# Template for Tables - CapturePayment
################################################

AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

################################################
# Parameters
################################################
Parameters:
  Application:
    Type: String
  Module:
    Type: String
  Environment:
    Type: String
    Default: dev
    Description: Environment name
  LogLevel:
    Type: String
    Default: INFO
  RetentionInDays:
    Type: Number
    Default: 30
    Description: CloudWatch Logs retention period for Lambda functions
  NodeLayerArn:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Node Layer NodeDependenciesLayer ARN
  EventBusName:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Event Bus Name


Globals:
  Function:
    Runtime: nodejs16.x
    Handler: index.handler
    Layers:
      - !Ref NodeLayerArn
    Timeout: 5
    Tracing: Active
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        LOG_LEVEL: !Ref LogLevel

################################################
# Resources
################################################
Resources:
  # CapturePaymentTable:
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: !Sub ${Application}-${Environment}-CapturePayment
  #     Tags:
  #       - Key: "Environment"
  #         Value: !Ref Environment
  #       - Key: "Application"
  #         Value: !Ref Application
  #     AttributeDefinitions:
  #       - AttributeName: CapturePayment
  #         AttributeType: S
  #     KeySchema:
  #       - AttributeName: CapturePayment
  #         KeyType: HASH
  #     GlobalSecondaryIndexes:
  #       - IndexName: byDeviceUserId
  #         KeySchema:
  #           - AttributeName: userId
  #             KeyType: HASH
  #         Projection:
  #           ProjectionType: ALL
  #     StreamSpecification:
  #       StreamViewType: NEW_AND_OLD_IMAGES
  #     BillingMode: PAY_PER_REQUEST
  #     SSESpecification:
  #       SSEEnabled: true
  #     PointInTimeRecoverySpecification:
  #       PointInTimeRecoveryEnabled: true
  #   DeletionPolicy: Retain

  ################################################
  # Functions
  ################################################
  ManageCapturePayment:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Application}-${Environment}-ManageCapturePayment-Function
      Handler: manage_CapturePayment.handler
      CodeUri: ./src
      MemorySize: 768
      Tags:
        Application: !Ref Application
        Environment: !Ref Environment
        Module: !Ref Module
      Environment:
        Variables:
          Application: !Ref Application
          ORDER_SHIPMENT_TABLE: !Sub ${Application}-${Environment}-OrderShipment
          LOG_LEVEL: !Ref LogLevel
      Policies:
        - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
                - dynamodb:Query
                - dynamodb:Scan
                - dynamodb:GetItem
              Resource:
                - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${Application}-${Environment}-ManageCapturePayment-Function"
                - !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${Application}-${Environment}-OrderShipment"
  ManageCapturePaymentLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ManageCapturePayment}"
      RetentionInDays: !Ref RetentionInDays
  ################################################
  # Event Bus Lambda Rule
  ################################################
  CapturePaymentEventRule:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: !Ref EventBusName
      EventPattern:
        source:
          - !Sub ${Application}-${Environment}-ManageOrderShipment-Function
        detail-type:
          - transaction
      Targets:
        - Id: capture-payment
          Arn: !GetAtt ManageCapturePayment.Arn
