################################################
# Template for Tables - CapturePayment
################################################

AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

################################################
# Parameters
################################################
Parameters:
  Application:
    Type: String
  Module:
    Type: String
  Environment:
    Type: String
    Default: dev
    Description: Environment name
  LogLevel:
    Type: String
    Default: INFO
  RetentionInDays:
    Type: Number
    Default: 30
    Description: CloudWatch Logs retention period for Lambda functions
  NodeLayerArn:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Node Layer NodeDependenciesLayer ARN
  OrderEventBusName:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Order Event Bus Name

Globals:
  Function:
    Runtime: nodejs16.x
    Handler: index.handler
    Layers:
      - !Ref NodeLayerArn
    Timeout: 5
    Tracing: Active
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        LOG_LEVEL: !Ref LogLevel

################################################
# Resources
################################################
Resources:
  ################################################
  # Functions
  ################################################
  ManageVisionWinePOS:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Application}-${Environment}-ManageVisionWinePOS-Function
      Handler: manage_visionWinePOS.handler
      CodeUri: ./src
      MemorySize: 768
      Tags:
        Application: !Ref Application
        Environment: !Ref Environment
        Module: !Ref Module
      Environment:
        Variables:
          Application: !Ref Application
          ORDER_SHIPMENT_TABLE: !Sub ${Application}-${Environment}-OrderShipment
          ORDER_TABLE: !Sub ${Application}-${Environment}-Order
          CUSTOMER_PROFILE_TABLE: !Sub ${Application}-${Environment}-CustomerProfile
          API_URL_ORDERS: https://br-family-jersey-city.vznlink.com/orders
          API_URL_REFUNDS: https://br-family-jersey-city.vznlink.com/refunds
          LOG_LEVEL: !Ref LogLevel
      Policies:
        - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
                - dynamodb:Query
                - dynamodb:Scan
                - dynamodb:GetItem
              Resource:
                - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${Application}-${Environment}-ManageVisionWinePOS-Function"
                - !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${Application}-${Environment}-OrderShipment"
                - !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${Application}-${Environment}-Order"
                - !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${Application}-${Environment}-CustomerProfile"
      Events:
        RuleEvent:
          Type: EventBridgeRule
          Properties:
            EventBusName: !Ref OrderEventBusName
            Target:
              Id: create-pos
            Pattern:
              source:
                - !Sub ${Application}-${Environment}-ManageOrder-Function
  ManageVisionWinePOSLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ManageVisionWinePOS}"
      RetentionInDays: !Ref RetentionInDays
  ################################################
  # Event Bus Lambda Rule
  ################################################
  WinePOSRule:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: !Ref OrderEventBusName
      EventPattern:
        source:
          - !Sub ${Application}-${Environment}-ManageOrder-Function
        detail-type:
          - Create-POS
      Targets:
        - Id: create-pos
          Arn: !GetAtt ManageVisionWinePOS.Arn
