version = 0.1

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "spirits-dev-checkoutWrapper-datasource"
s3_bucket = "843219620739-spirits-dev-samdeploy"
s3_prefix = "spirits-dev-checkoutWrapper-datasource"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Application=\"spirits\" Module=\"customer\" Environment=\"dev\" LogLevel=\"INFO\" RetentionInDays=\"30\" EventBusName=\"/spirits/dev/platform/eventbus/arn\" NodeLayerArn=\"/spirits/dev/shared/nodelayer/arn\" QueryLimit=\"20\" ApiId=\"/spirits/dev/customer/customerapi/id\" ElasticSearchDomainEndpoint=\"/spirits/dev/elasticsearch/domain/endpoint\" GetCartFunctionId=\"/spirits/dev/customer/cartFunction/id\" SearchStoreFunctionId=\"/spirits/dev/customer/searchStoreFunction/id\" CreatePaymentIntentFunctionId=\"/spirits/dev/customer/createPaymentIntent/id\" CalculateTaxFunctionId=\"/spirits/dev/customer/calculateTaxFunction/id\" GetCustomerProfileFunctionId=\"/spirits/dev/customer/getCustomerProfileFunction/id\" PaymentMethodsListFunction=\"/spirits/dev/customer/paymentMethodsList/id\""

[devdep]
[devdep.deploy]
[devdep.deploy.parameters]
stack_name = "spirits-dev-checkoutWrapper-dep-datasource"
s3_bucket = "843219620739-spirits-dev-samdeploy"
s3_prefix = "spirits-dev-checkoutWrapper-dep-datasource"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Application=\"spirits\" Module=\"customer\" Environment=\"dev\" LogLevel=\"INFO\" RetentionInDays=\"30\" EventBusName=\"/spirits/dev/platform/eventbus/arn\" NodeLayerArn=\"/spirits/dev/shared/nodelayer/arn\" QueryLimit=\"20\" ApiId=\"/spirits/dev/customer/customerapi/id\" ElasticSearchDomainEndpoint=\"/spirits/dev/elasticsearch/domain/endpoint\""

[dev2]
[dev2.deploy]
[dev2.deploy.parameters]
stack_name = "spirits-dev2-checkoutWrapper-datasource"
s3_bucket = "843219620739-spirits-dev-samdeploy"
s3_prefix = "spirits-dev2-checkoutWrapper-datasource"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Application=\"spirits\" Module=\"customer\" Environment=\"dev2\" LogLevel=\"INFO\" RetentionInDays=\"30\" EventBusName=\"/spirits/dev2/platform/eventbus/arn\" NodeLayerArn=\"/spirits/dev2/shared/nodelayer/arn\" QueryLimit=\"20\" ApiId=\"/spirits/dev2/customer/customerapi/id\" ElasticSearchDomainEndpoint=\"/spirits/dev/elasticsearch/domain/endpoint\""

[sit]
[sit.deploy]
[sit.deploy.parameters]
stack_name = "spirits-sit-checkoutWrapper-datasource"
s3_bucket = "843219620739-spirits-dev-samdeploy"
s3_prefix = "spirits-sit-checkoutWrapper-datasource"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Application=\"spirits\" Module=\"customer\" Environment=\"sit\" LogLevel=\"INFO\" RetentionInDays=\"30\" EventBusName=\"/spirits/sit/platform/eventbus/arn\" NodeLayerArn=\"/spirits/sit/shared/nodelayer/arn\" QueryLimit=\"20\" ApiId=\"/spirits/sit/customer/customerapi/id\" ElasticSearchDomainEndpoint=\"/spirits/sit/elasticsearch/domain/endpoint\" GetCartFunctionId=\"/spirits/sit/customer/cartFunction/id\" SearchStoreFunctionId=\"/spirits/sit/customer/searchStoreFunction/id\" CreatePaymentIntentFunctionId=\"/spirits/sit/customer/createPaymentIntent/id\" CalculateTaxFunctionId=\"/spirits/sit/customer/calculateTaxFunction/id\" GetCustomerProfileFunctionId=\"/spirits/sit/customer/getCustomerProfileFunction/id\" PaymentMethodsListFunction=\"/spirits/sit/customer/paymentMethodsList/id\""

[prd]
[prd.deploy]
[prd.deploy.parameters]
stack_name = "spirits-prd-checkoutWrapper-datasource"
s3_bucket = "409907184267-spirits-prd-samdeploy"
s3_prefix = "spirits-prd-checkoutWrapper-datasource"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Application=\"spirits\" Module=\"customer\" Environment=\"prd\" LogLevel=\"INFO\" RetentionInDays=\"30\" EventBusName=\"/spirits/prd/platform/eventbus/arn\" NodeLayerArn=\"/spirits/prd/shared/nodelayer/arn\" QueryLimit=\"20\" ApiId=\"/spirits/prd/customer/customerapi/id\" ElasticSearchDomainEndpoint=\"/spirits/prd/elasticsearch/domain/endpoint\" GetCartFunctionId=\"/spirits/prd/customer/cartFunction/id\" SearchStoreFunctionId=\"/spirits/prd/customer/searchStoreFunction/id\" CreatePaymentIntentFunctionId=\"/spirits/prd/customer/createPaymentIntent/id\" CalculateTaxFunctionId=\"/spirits/prd/customer/calculateTaxFunction/id\" GetCustomerProfileFunctionId=\"/spirits/prd/customer/getCustomerProfileFunction/id\" PaymentMethodsListFunction=\"/spirits/prd/customer/paymentMethodsList/id\""
